---

- name: Create mentor dir
  file:
    path: "{{ mentor_root }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- include: spyglass.yml
  tags: [setup]

- include: workshop.yml
  tags: [setup]

- include: teardown.yml
  tags: [never, teardown]

